export const COACHING_STYLES_OPTIONS = [
  { value: 'supportive', label: 'Supportive & Gentle' },
  { value: 'goal-focused', label: 'Goal-Focused' },
  { value: 'holistic', label: 'Holistic' },
  { value: 'motivational', label: 'Motivational' },
  { value: 'educational', label: 'Educational' },
];

export const CULTURE_EXPERIENCE_OPTIONS = [
  { value: 'south-asian', label: 'South Asian' },
  { value: 'east-asian', label: 'East Asian' },
  { value: 'african-american', label: 'African-American / Black' },
  { value: 'latinx-hispanic', label: 'Latinx / Hispanic' },
  { value: 'middle-eastern-north-african', label: 'Middle Eastern / North African' },
  { value: 'white-european', label: 'White / European' },
  { value: 'lgbtq', label: 'LGBTQ+' },
  { value: 'comfortable-with-all', label: 'Comfortable with all' },
];

export const CONSULTATION_TYPES = [
  { label: 'Chat', value: 'chat' },
  { label: 'Audio', value: 'audio' },
  { label: 'Video', value: 'video' },
];

export const AFFILIATE_CHANNELS = [
  { label: 'Website or Blog', value: 'website-blog' },
  { label: 'Email Newsletter or SMS List', value: 'email-sms' },
  { label: 'YouTube or Video Content', value: 'youtube-video' },
  { label: 'Social Media (Instagram, Facebook, TikTok, etc.)', value: 'social-media' },
  { label: 'Podcast or Audio Platform', value: 'podcast-audio' },
  { label: 'Online Courses or Membership Communities', value: 'online-courses' },
  { label: 'Paid Ads (Google, Meta, Native, etc.)', value: 'paid-ads' },
  { label: 'Coupon, Deal, or Cashback Sites', value: 'coupon-deals' },
  { label: 'Webinars or Live Events', value: 'webinars-events' },
  { label: 'Other', value: 'other' },
];

export const TIME_ZONES = [
  {
    value: 'Dateline Standard Time',
    abbr: 'DST',
    offset: -12,
    isdst: false,
    text: '(UTC-12:00) International Date Line West',
    label: '(UTC-12:00) International Date Line West',
    utc: ['Etc/GMT+12'],
  },
  {
    value: 'UTC-11',
    abbr: 'U',
    offset: -11,
    isdst: false,
    text: '(UTC-11:00) Coordinated Universal Time-11',
    label: '(UTC-11:00) Coordinated Universal Time-11',
    utc: ['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
  },
  {
    value: 'Hawaiian Standard Time',
    abbr: 'HST',
    offset: -10,
    isdst: false,
    text: '(UTC-10:00) Hawaii',
    label: '(UTC-10:00) Hawaii',
    utc: ['Etc/GMT+10', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Rarotonga', 'Pacific/Tahiti'],
  },
  {
    value: 'Alaskan Standard Time',
    abbr: 'AKDT',
    offset: -8,
    isdst: true,
    text: '(UTC-09:00) Alaska',
    label: '(UTC-09:00) Alaska',
    utc: ['America/Anchorage', 'America/Juneau', 'America/Nome', 'America/Sitka', 'America/Yakutat'],
  },
  {
    value: 'Pacific Standard Time (Mexico)',
    abbr: 'PDT',
    offset: -7,
    isdst: true,
    text: '(UTC-08:00) Baja California',
    label: '(UTC-08:00) Baja California',
    utc: ['America/Santa_Isabel'],
  },
  {
    value: 'Pacific Daylight Time',
    abbr: 'PDT',
    offset: -7,
    isdst: true,
    text: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
    label: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
    utc: ['America/Los_Angeles', 'America/Tijuana', 'America/Vancouver'],
  },
  {
    value: 'Pacific Standard Time',
    abbr: 'PST',
    offset: -8,
    isdst: false,
    text: '(UTC-08:00) Pacific Standard Time (US & Canada)',
    label: '(UTC-08:00) Pacific Standard Time (US & Canada)',
    utc: ['America/Los_Angeles', 'America/Tijuana', 'America/Vancouver', 'PST8PDT'],
  },
  {
    value: 'US Mountain Standard Time',
    abbr: 'UMST',
    offset: -7,
    isdst: false,
    text: '(UTC-07:00) Arizona',
    label: '(UTC-07:00) Arizona',
    utc: [
      'America/Creston',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Hermosillo',
      'America/Phoenix',
      'America/Whitehorse',
      'Etc/GMT+7',
    ],
  },
  {
    value: 'Mountain Standard Time (Mexico)',
    abbr: 'MDT',
    offset: -6,
    isdst: true,
    text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    utc: ['America/Chihuahua', 'America/Mazatlan'],
  },
  {
    value: 'Mountain Standard Time',
    abbr: 'MDT',
    offset: -6,
    isdst: true,
    text: '(UTC-07:00) Mountain Time (US & Canada)',
    label: '(UTC-07:00) Mountain Time (US & Canada)',
    utc: [
      'America/Boise',
      'America/Cambridge_Bay',
      'America/Denver',
      'America/Edmonton',
      'America/Inuvik',
      'America/Ojinaga',
      'America/Yellowknife',
      'MST7MDT',
    ],
  },
  {
    value: 'Central America Standard Time',
    abbr: 'CAST',
    offset: -6,
    isdst: false,
    text: '(UTC-06:00) Central America',
    label: '(UTC-06:00) Central America',
    utc: [
      'America/Belize',
      'America/Costa_Rica',
      'America/El_Salvador',
      'America/Guatemala',
      'America/Managua',
      'America/Tegucigalpa',
      'Etc/GMT+6',
      'Pacific/Galapagos',
    ],
  },
  {
    value: 'Central Standard Time',
    abbr: 'CDT',
    offset: -5,
    isdst: true,
    text: '(UTC-06:00) Central Time (US & Canada)',
    label: '(UTC-06:00) Central Time (US & Canada)',
    utc: [
      'America/Chicago',
      'America/Indiana/Knox',
      'America/Indiana/Tell_City',
      'America/Matamoros',
      'America/Menominee',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Resolute',
      'America/Winnipeg',
      'CST6CDT',
    ],
  },
  {
    value: 'Central Standard Time (Mexico)',
    abbr: 'CDT',
    offset: -5,
    isdst: true,
    text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    utc: [
      'America/Bahia_Banderas',
      'America/Cancun',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
    ],
  },
  {
    value: 'Canada Central Standard Time',
    abbr: 'CCST',
    offset: -6,
    isdst: false,
    text: '(UTC-06:00) Saskatchewan',
    label: '(UTC-06:00) Saskatchewan',
    utc: ['America/Regina', 'America/Swift_Current'],
  },
  {
    value: 'SA Pacific Standard Time',
    abbr: 'SPST',
    offset: -5,
    isdst: false,
    text: '(UTC-05:00) Bogota, Lima, Quito',
    label: '(UTC-05:00) Bogota, Lima, Quito',
    utc: [
      'America/Bogota',
      'America/Cayman',
      'America/Coral_Harbour',
      'America/Eirunepe',
      'America/Guayaquil',
      'America/Jamaica',
      'America/Lima',
      'America/Panama',
      'America/Rio_Branco',
      'Etc/GMT+5',
    ],
  },
  {
    value: 'Eastern Standard Time',
    abbr: 'EST',
    offset: -5,
    isdst: false,
    text: '(UTC-05:00) Eastern Time (US & Canada)',
    label: '(UTC-05:00) Eastern Time (US & Canada)',
    utc: [
      'America/Detroit',
      'America/Havana',
      'America/Indiana/Petersburg',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/New_York',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
    ],
  },
  {
    value: 'Eastern Daylight Time',
    abbr: 'EDT',
    offset: -4,
    isdst: true,
    text: '(UTC-04:00) Eastern Daylight Time (US & Canada)',
    label: '(UTC-04:00) Eastern Daylight Time (US & Canada)',
    utc: [
      'America/Detroit',
      'America/Havana',
      'America/Indiana/Petersburg',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/New_York',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
    ],
  },
  {
    value: 'US Eastern Standard Time',
    abbr: 'UEDT',
    offset: -5,
    isdst: false,
    text: '(UTC-05:00) Indiana (East)',
    label: '(UTC-05:00) Indiana (East)',
    utc: ['America/Indiana/Marengo', 'America/Indiana/Vevay', 'America/Indianapolis'],
  },
  {
    value: 'Venezuela Standard Time',
    abbr: 'VST',
    offset: -4.5,
    isdst: false,
    text: '(UTC-04:30) Caracas',
    label: '(UTC-04:30) Caracas',
    utc: ['America/Caracas'],
  },
  {
    value: 'Paraguay Standard Time',
    abbr: 'PYT',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Asuncion',
    label: '(UTC-04:00) Asuncion',
    utc: ['America/Asuncion'],
  },
  {
    value: 'Atlantic Standard Time',
    abbr: 'ADT',
    offset: -3,
    isdst: true,
    text: '(UTC-04:00) Atlantic Time (Canada)',
    label: '(UTC-04:00) Atlantic Time (Canada)',
    utc: [
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Moncton',
      'America/Thule',
      'Atlantic/Bermuda',
    ],
  },
  {
    value: 'Central Brazilian Standard Time',
    abbr: 'CBST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Cuiaba',
    label: '(UTC-04:00) Cuiaba',
    utc: ['America/Campo_Grande', 'America/Cuiaba'],
  },
  {
    value: 'SA Western Standard Time',
    abbr: 'SWST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    label: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    utc: [
      'America/Anguilla',
      'America/Antigua',
      'America/Aruba',
      'America/Barbados',
      'America/Blanc-Sablon',
      'America/Boa_Vista',
      'America/Curacao',
      'America/Dominica',
      'America/Grand_Turk',
      'America/Grenada',
      'America/Guadeloupe',
      'America/Guyana',
      'America/Kralendijk',
      'America/La_Paz',
      'America/Lower_Princes',
      'America/Manaus',
      'America/Marigot',
      'America/Martinique',
      'America/Montserrat',
      'America/Port_of_Spain',
      'America/Porto_Velho',
      'America/Puerto_Rico',
      'America/Santo_Domingo',
      'America/St_Barthelemy',
      'America/St_Kitts',
      'America/St_Lucia',
      'America/St_Thomas',
      'America/St_Vincent',
      'America/Tortola',
      'Etc/GMT+4',
    ],
  },
  {
    value: 'Pacific SA Standard Time',
    abbr: 'PSST',
    offset: -4,
    isdst: false,
    text: '(UTC-04:00) Santiago',
    label: '(UTC-04:00) Santiago',
    utc: ['America/Santiago', 'Antarctica/Palmer'],
  },
  {
    value: 'Newfoundland Standard Time',
    abbr: 'NDT',
    offset: -2.5,
    isdst: true,
    text: '(UTC-03:30) Newfoundland',
    label: '(UTC-03:30) Newfoundland',
    utc: ['America/St_Johns'],
  },
  {
    value: 'E. South America Standard Time',
    abbr: 'ESAST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Brasilia',
    label: '(UTC-03:00) Brasilia',
    utc: ['America/Sao_Paulo'],
  },
  {
    value: 'Argentina Standard Time',
    abbr: 'AST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Buenos Aires',
    label: '(UTC-03:00) Buenos Aires',
    utc: [
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Catamarca',
      'America/Argentina/Cordoba',
      'America/Argentina/Jujuy',
      'America/Argentina/La_Rioja',
      'America/Argentina/Mendoza',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'America/Buenos_Aires',
      'America/Catamarca',
      'America/Cordoba',
      'America/Jujuy',
      'America/Mendoza',
    ],
  },
  {
    value: 'SA Eastern Standard Time',
    abbr: 'SEST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Cayenne, Fortaleza',
    label: '(UTC-03:00) Cayenne, Fortaleza',
    utc: [
      'America/Araguaina',
      'America/Belem',
      'America/Cayenne',
      'America/Fortaleza',
      'America/Maceio',
      'America/Paramaribo',
      'America/Recife',
      'America/Santarem',
      'Antarctica/Rothera',
      'Atlantic/Stanley',
      'Etc/GMT+3',
    ],
  },
  {
    value: 'Greenland Standard Time',
    abbr: 'GDT',
    offset: -3,
    isdst: true,
    text: '(UTC-03:00) Greenland',
    label: '(UTC-03:00) Greenland',
    utc: ['America/Godthab'],
  },
  {
    value: 'Montevideo Standard Time',
    abbr: 'MST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Montevideo',
    label: '(UTC-03:00) Montevideo',
    utc: ['America/Montevideo'],
  },
  {
    value: 'Bahia Standard Time',
    abbr: 'BST',
    offset: -3,
    isdst: false,
    text: '(UTC-03:00) Salvador',
    label: '(UTC-03:00) Salvador',
    utc: ['America/Bahia'],
  },
  {
    value: 'UTC-02',
    abbr: 'U',
    offset: -2,
    isdst: false,
    text: '(UTC-02:00) Coordinated Universal Time-02',
    label: '(UTC-02:00) Coordinated Universal Time-02',
    utc: ['America/Noronha', 'Atlantic/South_Georgia', 'Etc/GMT+2'],
  },
  {
    value: 'Mid-Atlantic Standard Time',
    abbr: 'MDT',
    offset: -1,
    isdst: true,
    text: '(UTC-02:00) Mid-Atlantic - Old',
    label: '(UTC-02:00) Mid-Atlantic - Old',
    utc: [],
  },
  {
    value: 'Azores Standard Time',
    abbr: 'ADT',
    offset: 0,
    isdst: true,
    text: '(UTC-01:00) Azores',
    label: '(UTC-01:00) Azores',
    utc: ['America/Scoresbysund', 'Atlantic/Azores'],
  },
  {
    value: 'Cape Verde Standard Time',
    abbr: 'CVST',
    offset: -1,
    isdst: false,
    text: '(UTC-01:00) Cape Verde Is.',
    label: '(UTC-01:00) Cape Verde Is.',
    utc: ['Atlantic/Cape_Verde', 'Etc/GMT+1'],
  },
  {
    value: 'Morocco Standard Time',
    abbr: 'MDT',
    offset: 1,
    isdst: true,
    text: '(UTC) Casablanca',
    label: '(UTC) Casablanca',
    utc: ['Africa/Casablanca', 'Africa/El_Aaiun'],
  },
  {
    value: 'UTC',
    abbr: 'UTC',
    offset: 0,
    isdst: false,
    text: '(UTC) Coordinated Universal Time',
    label: '(UTC) Coordinated Universal Time',
    utc: ['America/Danmarkshavn', 'Etc/GMT'],
  },
  {
    value: 'GMT Standard Time',
    abbr: 'GMT',
    offset: 0,
    isdst: false,
    text: '(UTC) Edinburgh, London',
    label: '(UTC) Edinburgh, London',
    utc: ['Europe/Isle_of_Man', 'Europe/Guernsey', 'Europe/Jersey', 'Europe/London'],
  },
  {
    value: 'British Summer Time',
    abbr: 'BST',
    offset: 1,
    isdst: true,
    text: '(UTC+01:00) Edinburgh, London',
    label: '(UTC+01:00) Edinburgh, London',
    utc: ['Europe/Isle_of_Man', 'Europe/Guernsey', 'Europe/Jersey', 'Europe/London'],
  },
  {
    value: 'GMT Standard Time',
    abbr: 'GDT',
    offset: 1,
    isdst: true,
    text: '(UTC) Dublin, Lisbon',
    label: '(UTC) Dublin, Lisbon',
    utc: ['Atlantic/Canary', 'Atlantic/Faeroe', 'Atlantic/Madeira', 'Europe/Dublin', 'Europe/Lisbon'],
  },
  {
    value: 'Greenwich Standard Time',
    abbr: 'GST',
    offset: 0,
    isdst: false,
    text: '(UTC) Monrovia, Reykjavik',
    label: '(UTC) Monrovia, Reykjavik',
    utc: [
      'Africa/Abidjan',
      'Africa/Accra',
      'Africa/Bamako',
      'Africa/Banjul',
      'Africa/Bissau',
      'Africa/Conakry',
      'Africa/Dakar',
      'Africa/Freetown',
      'Africa/Lome',
      'Africa/Monrovia',
      'Africa/Nouakchott',
      'Africa/Ouagadougou',
      'Africa/Sao_Tome',
      'Atlantic/Reykjavik',
      'Atlantic/St_Helena',
    ],
  },
  {
    value: 'W. Europe Standard Time',
    abbr: 'WEDT',
    offset: 2,
    isdst: true,
    text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    utc: [
      'Arctic/Longyearbyen',
      'Europe/Amsterdam',
      'Europe/Andorra',
      'Europe/Berlin',
      'Europe/Busingen',
      'Europe/Gibraltar',
      'Europe/Luxembourg',
      'Europe/Malta',
      'Europe/Monaco',
      'Europe/Oslo',
      'Europe/Rome',
      'Europe/San_Marino',
      'Europe/Stockholm',
      'Europe/Vaduz',
      'Europe/Vatican',
      'Europe/Vienna',
      'Europe/Zurich',
    ],
  },
  {
    value: 'Central Europe Standard Time',
    abbr: 'CEDT',
    offset: 2,
    isdst: true,
    text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    utc: [
      'Europe/Belgrade',
      'Europe/Bratislava',
      'Europe/Budapest',
      'Europe/Ljubljana',
      'Europe/Podgorica',
      'Europe/Prague',
      'Europe/Tirane',
    ],
  },
  {
    value: 'Romance Standard Time',
    abbr: 'RDT',
    offset: 2,
    isdst: true,
    text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    utc: ['Africa/Ceuta', 'Europe/Brussels', 'Europe/Copenhagen', 'Europe/Madrid', 'Europe/Paris'],
  },
  {
    value: 'Central European Standard Time',
    abbr: 'CEDT',
    offset: 2,
    isdst: true,
    text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    utc: ['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb'],
  },
  {
    value: 'W. Central Africa Standard Time',
    abbr: 'WCAST',
    offset: 1,
    isdst: false,
    text: '(UTC+01:00) West Central Africa',
    label: '(UTC+01:00) West Central Africa',
    utc: [
      'Africa/Algiers',
      'Africa/Bangui',
      'Africa/Brazzaville',
      'Africa/Douala',
      'Africa/Kinshasa',
      'Africa/Lagos',
      'Africa/Libreville',
      'Africa/Luanda',
      'Africa/Malabo',
      'Africa/Ndjamena',
      'Africa/Niamey',
      'Africa/Porto-Novo',
      'Africa/Tunis',
      'Etc/GMT-1',
    ],
  },
  {
    value: 'Namibia Standard Time',
    abbr: 'NST',
    offset: 1,
    isdst: false,
    text: '(UTC+01:00) Windhoek',
    label: '(UTC+01:00) Windhoek',
    utc: ['Africa/Windhoek'],
  },
  {
    value: 'GTB Standard Time',
    abbr: 'GDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) Athens, Bucharest',
    label: '(UTC+02:00) Athens, Bucharest',
    utc: ['Asia/Nicosia', 'Europe/Athens', 'Europe/Bucharest', 'Europe/Chisinau'],
  },
  {
    value: 'Middle East Standard Time',
    abbr: 'MEDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) Beirut',
    label: '(UTC+02:00) Beirut',
    utc: ['Asia/Beirut'],
  },
  {
    value: 'Egypt Standard Time',
    abbr: 'EST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Cairo',
    label: '(UTC+02:00) Cairo',
    utc: ['Africa/Cairo'],
  },
  {
    value: 'Syria Standard Time',
    abbr: 'SDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) Damascus',
    label: '(UTC+02:00) Damascus',
    utc: ['Asia/Damascus'],
  },
  {
    value: 'E. Europe Standard Time',
    abbr: 'EEDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) E. Europe',
    label: '(UTC+02:00) E. Europe',
    utc: [
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
      'Europe/Helsinki',
      'Europe/Kyiv',
      'Europe/Mariehamn',
      'Europe/Nicosia',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhhorod',
      'Europe/Vilnius',
      'Europe/Zaporizhzhia',
    ],
  },
  {
    value: 'South Africa Standard Time',
    abbr: 'SAST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Harare, Pretoria',
    label: '(UTC+02:00) Harare, Pretoria',
    utc: [
      'Africa/Blantyre',
      'Africa/Bujumbura',
      'Africa/Gaborone',
      'Africa/Harare',
      'Africa/Johannesburg',
      'Africa/Kigali',
      'Africa/Lubumbashi',
      'Africa/Lusaka',
      'Africa/Maputo',
      'Africa/Maseru',
      'Africa/Mbabane',
      'Etc/GMT-2',
    ],
  },
  {
    value: 'FLE Standard Time',
    abbr: 'FDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    label: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    utc: [
      'Europe/Helsinki',
      'Europe/Kyiv',
      'Europe/Mariehamn',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhhorod',
      'Europe/Vilnius',
      'Europe/Zaporizhzhia',
    ],
  },
  {
    value: 'Turkey Standard Time',
    abbr: 'TDT',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Istanbul',
    label: '(UTC+03:00) Istanbul',
    utc: ['Europe/Istanbul'],
  },
  {
    value: 'Israel Standard Time',
    abbr: 'JDT',
    offset: 3,
    isdst: true,
    text: '(UTC+02:00) Jerusalem',
    label: '(UTC+02:00) Jerusalem',
    utc: ['Asia/Jerusalem'],
  },
  {
    value: 'Libya Standard Time',
    abbr: 'LST',
    offset: 2,
    isdst: false,
    text: '(UTC+02:00) Tripoli',
    label: '(UTC+02:00) Tripoli',
    utc: ['Africa/Tripoli'],
  },
  {
    value: 'Jordan Standard Time',
    abbr: 'JST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Amman',
    label: '(UTC+03:00) Amman',
    utc: ['Asia/Amman'],
  },
  {
    value: 'Arabic Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Baghdad',
    label: '(UTC+03:00) Baghdad',
    utc: ['Asia/Baghdad'],
  },
  {
    value: 'Kaliningrad Standard Time',
    abbr: 'KST',
    offset: 3,
    isdst: false,
    text: '(UTC+02:00) Kaliningrad',
    label: '(UTC+02:00) Kaliningrad',
    utc: ['Europe/Kaliningrad'],
  },
  {
    value: 'Arab Standard Time',
    abbr: 'AST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Kuwait, Riyadh',
    label: '(UTC+03:00) Kuwait, Riyadh',
    utc: ['Asia/Aden', 'Asia/Bahrain', 'Asia/Kuwait', 'Asia/Qatar', 'Asia/Riyadh'],
  },
  {
    value: 'E. Africa Standard Time',
    abbr: 'EAST',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Nairobi',
    label: '(UTC+03:00) Nairobi',
    utc: [
      'Africa/Addis_Ababa',
      'Africa/Asmera',
      'Africa/Dar_es_Salaam',
      'Africa/Djibouti',
      'Africa/Juba',
      'Africa/Kampala',
      'Africa/Khartoum',
      'Africa/Mogadishu',
      'Africa/Nairobi',
      'Antarctica/Syowa',
      'Etc/GMT-3',
      'Indian/Antananarivo',
      'Indian/Comoro',
      'Indian/Mayotte',
    ],
  },
  {
    value: 'Moscow Standard Time',
    abbr: 'MSK',
    offset: 3,
    isdst: false,
    text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
    label: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
    utc: ['Europe/Kirov', 'Europe/Moscow', 'Europe/Simferopol', 'Europe/Volgograd', 'Europe/Minsk'],
  },
  {
    value: 'Samara Time',
    abbr: 'SAMT',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
    label: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
    utc: ['Europe/Astrakhan', 'Europe/Samara', 'Europe/Ulyanovsk'],
  },
  {
    value: 'Iran Standard Time',
    abbr: 'IDT',
    offset: 4.5,
    isdst: true,
    text: '(UTC+03:30) Tehran',
    label: '(UTC+03:30) Tehran',
    utc: ['Asia/Tehran'],
  },
  {
    value: 'Arabian Standard Time',
    abbr: 'AST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Abu Dhabi, Muscat',
    label: '(UTC+04:00) Abu Dhabi, Muscat',
    utc: ['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4'],
  },
  {
    value: 'Azerbaijan Standard Time',
    abbr: 'ADT',
    offset: 5,
    isdst: true,
    text: '(UTC+04:00) Baku',
    label: '(UTC+04:00) Baku',
    utc: ['Asia/Baku'],
  },
  {
    value: 'Mauritius Standard Time',
    abbr: 'MST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Port Louis',
    label: '(UTC+04:00) Port Louis',
    utc: ['Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion'],
  },
  {
    value: 'Georgian Standard Time',
    abbr: 'GET',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Tbilisi',
    label: '(UTC+04:00) Tbilisi',
    utc: ['Asia/Tbilisi'],
  },
  {
    value: 'Caucasus Standard Time',
    abbr: 'CST',
    offset: 4,
    isdst: false,
    text: '(UTC+04:00) Yerevan',
    label: '(UTC+04:00) Yerevan',
    utc: ['Asia/Yerevan'],
  },
  {
    value: 'Afghanistan Standard Time',
    abbr: 'AST',
    offset: 4.5,
    isdst: false,
    text: '(UTC+04:30) Kabul',
    label: '(UTC+04:30) Kabul',
    utc: ['Asia/Kabul'],
  },
  {
    value: 'West Asia Standard Time',
    abbr: 'WAST',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Ashgabat, Tashkent',
    label: '(UTC+05:00) Ashgabat, Tashkent',
    utc: [
      'Antarctica/Mawson',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Ashgabat',
      'Asia/Dushanbe',
      'Asia/Oral',
      'Asia/Samarkand',
      'Asia/Tashkent',
      'Etc/GMT-5',
      'Indian/Kerguelen',
      'Indian/Maldives',
    ],
  },
  {
    value: 'Yekaterinburg Time',
    abbr: 'YEKT',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Yekaterinburg',
    label: '(UTC+05:00) Yekaterinburg',
    utc: ['Asia/Yekaterinburg'],
  },
  {
    value: 'Pakistan Standard Time',
    abbr: 'PKT',
    offset: 5,
    isdst: false,
    text: '(UTC+05:00) Islamabad, Karachi',
    label: '(UTC+05:00) Islamabad, Karachi',
    utc: ['Asia/Karachi'],
  },
  {
    value: 'India Standard Time',
    abbr: 'IST',
    offset: 5.5,
    isdst: false,
    text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    utc: ['Asia/Kolkata', 'Asia/Calcutta'],
  },
  {
    value: 'Sri Lanka Standard Time',
    abbr: 'SLST',
    offset: 5.5,
    isdst: false,
    text: '(UTC+05:30) Sri Jayawardenepura',
    label: '(UTC+05:30) Sri Jayawardenepura',
    utc: ['Asia/Colombo'],
  },
  {
    value: 'Nepal Standard Time',
    abbr: 'NST',
    offset: 5.75,
    isdst: false,
    text: '(UTC+05:45) Kathmandu',
    label: '(UTC+05:45) Kathmandu',
    utc: ['Asia/Kathmandu'],
  },
  {
    value: 'Central Asia Standard Time',
    abbr: 'CAST',
    offset: 6,
    isdst: false,
    text: '(UTC+06:00) Nur-Sultan (Astana)',
    label: '(UTC+06:00) Nur-Sultan (Astana)',
    utc: [
      'Antarctica/Vostok',
      'Asia/Almaty',
      'Asia/Bishkek',
      'Asia/Qyzylorda',
      'Asia/Urumqi',
      'Etc/GMT-6',
      'Indian/Chagos',
    ],
  },
  {
    value: 'Bangladesh Standard Time',
    abbr: 'BST',
    offset: 6,
    isdst: false,
    text: '(UTC+06:00) Dhaka',
    label: '(UTC+06:00) Dhaka',
    utc: ['Asia/Dhaka', 'Asia/Thimphu'],
  },
  {
    value: 'Myanmar Standard Time',
    abbr: 'MST',
    offset: 6.5,
    isdst: false,
    text: '(UTC+06:30) Yangon (Rangoon)',
    label: '(UTC+06:30) Yangon (Rangoon)',
    utc: ['Asia/Rangoon', 'Indian/Cocos'],
  },
  {
    value: 'SE Asia Standard Time',
    abbr: 'SAST',
    offset: 7,
    isdst: false,
    text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    label: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    utc: [
      'Antarctica/Davis',
      'Asia/Bangkok',
      'Asia/Hovd',
      'Asia/Jakarta',
      'Asia/Phnom_Penh',
      'Asia/Pontianak',
      'Asia/Saigon',
      'Asia/Vientiane',
      'Etc/GMT-7',
      'Indian/Christmas',
    ],
  },
  {
    value: 'N. Central Asia Standard Time',
    abbr: 'NCAST',
    offset: 7,
    isdst: false,
    text: '(UTC+07:00) Novosibirsk',
    label: '(UTC+07:00) Novosibirsk',
    utc: ['Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk'],
  },
  {
    value: 'China Standard Time',
    abbr: 'CST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    label: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    utc: ['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai'],
  },
  {
    value: 'North Asia Standard Time',
    abbr: 'NAST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Krasnoyarsk',
    label: '(UTC+08:00) Krasnoyarsk',
    utc: ['Asia/Krasnoyarsk'],
  },
  {
    value: 'Singapore Standard Time',
    abbr: 'MPST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Kuala Lumpur, Singapore',
    label: '(UTC+08:00) Kuala Lumpur, Singapore',
    utc: [
      'Asia/Brunei',
      'Asia/Kuala_Lumpur',
      'Asia/Kuching',
      'Asia/Makassar',
      'Asia/Manila',
      'Asia/Singapore',
      'Etc/GMT-8',
    ],
  },
  {
    value: 'W. Australia Standard Time',
    abbr: 'WAST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Perth',
    label: '(UTC+08:00) Perth',
    utc: ['Antarctica/Casey', 'Australia/Perth'],
  },
  {
    value: 'Taipei Standard Time',
    abbr: 'TST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Taipei',
    label: '(UTC+08:00) Taipei',
    utc: ['Asia/Taipei'],
  },
  {
    value: 'Ulaanbaatar Standard Time',
    abbr: 'UST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Ulaanbaatar',
    label: '(UTC+08:00) Ulaanbaatar',
    utc: ['Asia/Choibalsan', 'Asia/Ulaanbaatar'],
  },
  {
    value: 'North Asia East Standard Time',
    abbr: 'NAEST',
    offset: 8,
    isdst: false,
    text: '(UTC+08:00) Irkutsk',
    label: '(UTC+08:00) Irkutsk',
    utc: ['Asia/Irkutsk'],
  },
  {
    value: 'Japan Standard Time',
    abbr: 'JST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    label: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    utc: ['Asia/Dili', 'Asia/Jayapura', 'Asia/Tokyo', 'Etc/GMT-9', 'Pacific/Palau'],
  },
  {
    value: 'Korea Standard Time',
    abbr: 'KST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Seoul',
    label: '(UTC+09:00) Seoul',
    utc: ['Asia/Pyongyang', 'Asia/Seoul'],
  },
  {
    value: 'Cen. Australia Standard Time',
    abbr: 'CAST',
    offset: 9.5,
    isdst: false,
    text: '(UTC+09:30) Adelaide',
    label: '(UTC+09:30) Adelaide',
    utc: ['Australia/Adelaide', 'Australia/Broken_Hill'],
  },
  {
    value: 'AUS Central Standard Time',
    abbr: 'ACST',
    offset: 9.5,
    isdst: false,
    text: '(UTC+09:30) Darwin',
    label: '(UTC+09:30) Darwin',
    utc: ['Australia/Darwin'],
  },
  {
    value: 'E. Australia Standard Time',
    abbr: 'EAST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Brisbane',
    label: '(UTC+10:00) Brisbane',
    utc: ['Australia/Brisbane', 'Australia/Lindeman'],
  },
  {
    value: 'AUS Eastern Standard Time',
    abbr: 'AEST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Canberra, Melbourne, Sydney',
    label: '(UTC+10:00) Canberra, Melbourne, Sydney',
    utc: ['Australia/Melbourne', 'Australia/Sydney'],
  },
  {
    value: 'West Pacific Standard Time',
    abbr: 'WPST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Guam, Port Moresby',
    label: '(UTC+10:00) Guam, Port Moresby',
    utc: [
      'Antarctica/DumontDUrville',
      'Etc/GMT-10',
      'Pacific/Guam',
      'Pacific/Port_Moresby',
      'Pacific/Saipan',
      'Pacific/Truk',
    ],
  },
  {
    value: 'Tasmania Standard Time',
    abbr: 'TST',
    offset: 10,
    isdst: false,
    text: '(UTC+10:00) Hobart',
    label: '(UTC+10:00) Hobart',
    utc: ['Australia/Currie', 'Australia/Hobart'],
  },
  {
    value: 'Yakutsk Standard Time',
    abbr: 'YST',
    offset: 9,
    isdst: false,
    text: '(UTC+09:00) Yakutsk',
    label: '(UTC+09:00) Yakutsk',
    utc: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Yakutsk'],
  },
  {
    value: 'Central Pacific Standard Time',
    abbr: 'CPST',
    offset: 11,
    isdst: false,
    text: '(UTC+11:00) Solomon Is., New Caledonia',
    label: '(UTC+11:00) Solomon Is., New Caledonia',
    utc: [
      'Antarctica/Macquarie',
      'Etc/GMT-11',
      'Pacific/Efate',
      'Pacific/Guadalcanal',
      'Pacific/Kosrae',
      'Pacific/Noumea',
      'Pacific/Ponape',
    ],
  },
  {
    value: 'Vladivostok Standard Time',
    abbr: 'VST',
    offset: 11,
    isdst: false,
    text: '(UTC+11:00) Vladivostok',
    label: '(UTC+11:00) Vladivostok',
    utc: ['Asia/Sakhalin', 'Asia/Ust-Nera', 'Asia/Vladivostok'],
  },
  {
    value: 'New Zealand Standard Time',
    abbr: 'NZST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Auckland, Wellington',
    label: '(UTC+12:00) Auckland, Wellington',
    utc: ['Antarctica/McMurdo', 'Pacific/Auckland'],
  },
  {
    value: 'UTC+12',
    abbr: 'U',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Coordinated Universal Time+12',
    label: '(UTC+12:00) Coordinated Universal Time+12',
    utc: [
      'Etc/GMT-12',
      'Pacific/Funafuti',
      'Pacific/Kwajalein',
      'Pacific/Majuro',
      'Pacific/Nauru',
      'Pacific/Tarawa',
      'Pacific/Wake',
      'Pacific/Wallis',
    ],
  },
  {
    value: 'Fiji Standard Time',
    abbr: 'FST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Fiji',
    label: '(UTC+12:00) Fiji',
    utc: ['Pacific/Fiji'],
  },
  {
    value: 'Magadan Standard Time',
    abbr: 'MST',
    offset: 12,
    isdst: false,
    text: '(UTC+12:00) Magadan',
    label: '(UTC+12:00) Magadan',
    utc: ['Asia/Anadyr', 'Asia/Kamchatka', 'Asia/Magadan', 'Asia/Srednekolymsk'],
  },
  {
    value: 'Kamchatka Standard Time',
    abbr: 'KDT',
    offset: 13,
    isdst: true,
    text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    label: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    utc: ['Asia/Kamchatka'],
  },
  {
    value: 'Tonga Standard Time',
    abbr: 'TST',
    offset: 13,
    isdst: false,
    text: "(UTC+13:00) Nuku'alofa",
    label: "(UTC+13:00) Nuku'alofa",
    utc: ['Etc/GMT-13', 'Pacific/Enderbury', 'Pacific/Fakaofo', 'Pacific/Tongatapu'],
  },
  {
    value: 'Samoa Standard Time',
    abbr: 'SST',
    offset: 13,
    isdst: false,
    text: '(UTC+13:00) Samoa',
    label: '(UTC+13:00) Samoa',
    utc: ['Pacific/Apia'],
  },
];

export const COUNTRIES_CALLING_CODE = [
  { code: 'QA', name: 'Qatar', nativeName: 'قطر', flag: '🇶🇦', callingCode: '+974' },
  { code: 'AF', name: 'Afghanistan', nativeName: 'افغانستان', flag: '🇦🇫', callingCode: '+93' },
  { code: 'AL', name: 'Albania', nativeName: 'Shqipëri', flag: '🇦🇱', callingCode: '+355' },
  { code: 'DZ', name: 'Algeria', nativeName: 'الجزائر', flag: '🇩🇿', callingCode: '+213' },
  { code: 'AS', name: 'American Samoa', nativeName: 'Amerika Sāmoa', flag: '🇦🇸', callingCode: '+1684' },
  { code: 'AD', name: 'Andorra', nativeName: 'Andorra', flag: '🇦🇩', callingCode: '+376' },
  { code: 'AO', name: 'Angola', nativeName: 'Angola', flag: '🇦🇴', callingCode: '+244' },
  { code: 'AI', name: 'Anguilla', nativeName: 'Anguilla', flag: '🇦🇮', callingCode: '+1264' },
  { code: 'AQ', name: 'Antarctica', nativeName: 'Antarctica', flag: '🇦🇶', callingCode: '+672' },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    nativeName: 'Antigua and Barbuda',
    flag: '🇦🇬',
    callingCode: '+1268',
  },
  { code: 'AR', name: 'Argentina', nativeName: 'Argentina', flag: '🇦🇷', callingCode: '+54' },
  { code: 'AM', name: 'Armenia', nativeName: 'Հայաստան', flag: '🇦🇲', callingCode: '+374' },
  { code: 'AW', name: 'Aruba', nativeName: 'Aruba', flag: '🇦🇼', callingCode: '+297' },
  { code: 'AU', name: 'Australia', nativeName: 'Australia', flag: '🇦🇺', callingCode: '+61' },
  { code: 'AT', name: 'Austria', nativeName: 'Österreich', flag: '🇦🇹', callingCode: '+43' },
  { code: 'AZ', name: 'Azerbaijan', nativeName: 'Azərbaycan', flag: '🇦🇿', callingCode: '+994' },
  { code: 'BS', name: 'Bahamas', nativeName: 'Bahamas', flag: '🇧🇸', callingCode: '+1-242' },
  { code: 'BH', name: 'Bahrain', nativeName: 'البحرين', flag: '🇧🇭', callingCode: '+973' },
  { code: 'BD', name: 'Bangladesh', nativeName: 'বাংলাদেশ', flag: '🇧🇩', callingCode: '+880' },
  { code: 'BB', name: 'Barbados', nativeName: 'Barbados', flag: '🇧🇧', callingCode: '+1246' },
  { code: 'BY', name: 'Belarus', nativeName: 'Беларусь', flag: '🇧🇾', callingCode: '+375' },
  { code: 'BE', name: 'Belgium', nativeName: 'België', flag: '🇧🇪', callingCode: '+32' },
  { code: 'BZ', name: 'Belize', nativeName: 'Belize', flag: '🇧🇿', callingCode: '+501' },
  { code: 'BJ', name: 'Benin', nativeName: 'Bénin', flag: '🇧🇯', callingCode: '+229' },
  { code: 'BM', name: 'Bermuda', nativeName: 'Bermuda', flag: '🇧🇲', callingCode: '+1441' },
  { code: 'BT', name: 'Bhutan', nativeName: 'འབྲུག་ཡུལ་', flag: '🇧🇹', callingCode: '+975' },
  { code: 'BO', name: 'Bolivia', nativeName: 'Bolivia', flag: '🇧🇴', callingCode: '+591' },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
    flag: '🇧🇦',
    callingCode: '+387',
  },
  { code: 'BW', name: 'Botswana', nativeName: 'Botswana', flag: '🇧🇼', callingCode: '+267' },
  { code: 'BR', name: 'Brazil', nativeName: 'Brasil', flag: '🇧🇷', callingCode: '+55' },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    nativeName: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    callingCode: '+246',
  },
  { code: 'BN', name: 'Brunei', nativeName: 'Brunei', flag: '🇧🇳', callingCode: '+673' },
  { code: 'BG', name: 'Bulgaria', nativeName: 'България', flag: '🇧🇬', callingCode: '+359' },
  { code: 'BF', name: 'Burkina Faso', nativeName: 'Burkina Faso', flag: '🇧🇫', callingCode: '+226' },
  { code: 'BI', name: 'Burundi', nativeName: 'Burundi', flag: '🇧🇮', callingCode: '+257' },
  { code: 'CV', name: 'Cabo Verde', nativeName: 'Cabo Verde', flag: '🇨🇻', callingCode: '+238' },
  { code: 'KH', name: 'Cambodia', nativeName: 'កម្ពុជា', flag: '🇰🇭', callingCode: '+855' },
  { code: 'CM', name: 'Cameroon', nativeName: 'Cameroun', flag: '🇨🇲', callingCode: '+237' },
  { code: 'KY', name: 'Cayman Islands', nativeName: 'Cayman Islands', flag: '🇰🇾', callingCode: '+1345' },
  {
    code: 'CF',
    name: 'Central African Republic',
    nativeName: 'République centrafricaine',
    flag: '🇨🇫',
    callingCode: '+236',
  },
  { code: 'TD', name: 'Chad', nativeName: 'Tchad', flag: '🇹🇩', callingCode: '+235' },
  { code: 'CL', name: 'Chile', nativeName: 'Chile', flag: '🇨🇱', callingCode: '+56' },
  { code: 'CN', name: 'China', nativeName: '中国', flag: '🇨🇳', callingCode: '+86' },
  { code: 'CO', name: 'Colombia', nativeName: 'Colombia', flag: '🇨🇴', callingCode: '+57' },
  { code: 'KM', name: 'Comoros', nativeName: 'جزر القمر', flag: '🇰🇲', callingCode: '+269' },
  { code: 'CG', name: 'Congo (Brazzaville)', nativeName: 'Congo', flag: '🇨🇬', callingCode: '+242' },
  { code: 'CD', name: 'Congo (Kinshasa)', nativeName: 'Congo-Kinshasa', flag: '🇨🇩', callingCode: '+243' },
  { code: 'CR', name: 'Costa Rica', nativeName: 'Costa Rica', flag: '🇨🇷', callingCode: '+506' },
  { code: 'HR', name: 'Croatia', nativeName: 'Hrvatska', flag: '🇭🇷', callingCode: '+385' },
  { code: 'CU', name: 'Cuba', nativeName: 'Cuba', flag: '🇨🇺', callingCode: '+53' },
  { code: 'CY', name: 'Cyprus', nativeName: 'Κύπρος', flag: '🇨🇾', callingCode: '+357' },
  { code: 'CZ', name: 'Czechia', nativeName: 'Česko', flag: '🇨🇿', callingCode: '+420' },
  { code: 'DK', name: 'Denmark', nativeName: 'Danmark', flag: '🇩🇰', callingCode: '+45' },
  { code: 'DJ', name: 'Djibouti', nativeName: 'جيبوتي', flag: '🇩🇯', callingCode: '+253' },
  { code: 'DM', name: 'Dominica', nativeName: 'Dominica', flag: '🇩🇲', callingCode: '+1767' },
  {
    code: 'DO',
    name: 'Dominican Republic',
    nativeName: 'República Dominicana',
    flag: '🇩🇴',
    callingCode: '+1809',
  },
  { code: 'EC', name: 'Ecuador', nativeName: 'Ecuador', flag: '🇪🇨', callingCode: '+593' },
  { code: 'EG', name: 'Egypt', nativeName: 'مصر', flag: '🇪🇬', callingCode: '+20' },
  { code: 'SV', name: 'El Salvador', nativeName: 'El Salvador', flag: '🇸🇻', callingCode: '+503' },
  { code: 'GQ', name: 'Equatorial Guinea', nativeName: 'Guinea Ecuatorial', flag: '🇬🇶', callingCode: '+240' },
  { code: 'ER', name: 'Eritrea', nativeName: 'ኤርትራ', flag: '🇪🇷', callingCode: '+291' },
  { code: 'EE', name: 'Estonia', nativeName: 'Eesti', flag: '🇪🇪', callingCode: '+372' },
  { code: 'SZ', name: 'Eswatini', nativeName: 'Eswatini', flag: '🇸🇿', callingCode: '+268' },
  { code: 'ET', name: 'Ethiopia', nativeName: 'ኢትዮጵያ', flag: '🇪🇹', callingCode: '+251' },
  { code: 'FJ', name: 'Fiji', nativeName: 'Fiji', flag: '🇫🇯', callingCode: '+679' },
  { code: 'FI', name: 'Finland', nativeName: 'Suomi', flag: '🇫🇮', callingCode: '+358' },
  { code: 'FR', name: 'France', nativeName: 'France', flag: '🇫🇷', callingCode: '+33' },
  { code: 'GA', name: 'Gabon', nativeName: 'Gabon', flag: '🇬🇦', callingCode: '+241' },
  { code: 'GM', name: 'Gambia', nativeName: 'Gambia', flag: '🇬🇲', callingCode: '+220' },
  { code: 'GE', name: 'Georgia', nativeName: 'საქართველო', flag: '🇬🇪', callingCode: '+995' },
  { code: 'DE', name: 'Germany', nativeName: 'Deutschland', flag: '🇩🇪', callingCode: '+49' },
  { code: 'GH', name: 'Ghana', nativeName: 'Ghana', flag: '🇬🇭', callingCode: '+233' },
  { code: 'GI', name: 'Gibraltar', nativeName: 'Gibraltar', flag: '🇬🇮', callingCode: '+350' },
  { code: 'GR', name: 'Greece', nativeName: 'Ελλάδα', flag: '🇬🇷', callingCode: '+30' },
  { code: 'GL', name: 'Greenland', nativeName: 'Kalaallit Nunaat', flag: '🇬🇱', callingCode: '+299' },
  { code: 'GD', name: 'Grenada', nativeName: 'Grenada', flag: '🇬🇩', callingCode: '+1473' },
  { code: 'GU', name: 'Guam', nativeName: 'Guam', flag: '🇬🇺', callingCode: '+1671' },
  { code: 'GT', name: 'Guatemala', nativeName: 'Guatemala', flag: '🇬🇹', callingCode: '+502' },
  { code: 'GN', name: 'Guinea', nativeName: 'Guinée', flag: '🇬🇳', callingCode: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', nativeName: 'Guiné-Bissau', flag: '🇬🇼', callingCode: '+245' },
  { code: 'GY', name: 'Guyana', nativeName: 'Guyana', flag: '🇬🇾', callingCode: '+592' },
  { code: 'HT', name: 'Haiti', nativeName: 'Haïti', flag: '🇭🇹', callingCode: '+509' },
  { code: 'HN', name: 'Honduras', nativeName: 'Honduras', flag: '🇭🇳', callingCode: '+504' },
  { code: 'HK', name: 'Hong Kong', nativeName: '香港', flag: '🇭🇰', callingCode: '+852' },
  { code: 'HU', name: 'Hungary', nativeName: 'Magyarország', flag: '🇭🇺', callingCode: '+36' },
  { code: 'IS', name: 'Iceland', nativeName: 'Ísland', flag: '🇮🇸', callingCode: '+354' },
  { code: 'IN', name: 'India', nativeName: 'भारत', flag: '🇮🇳', callingCode: '+91' },
  { code: 'ID', name: 'Indonesia', nativeName: 'Indonesia', flag: '🇮🇩', callingCode: '+62' },
  { code: 'IR', name: 'Iran', nativeName: 'ایران', flag: '🇮🇷', callingCode: '+98' },
  { code: 'IQ', name: 'Iraq', nativeName: 'العراق', flag: '🇮🇶', callingCode: '+964' },
  { code: 'IE', name: 'Ireland', nativeName: 'Éire', flag: '🇮🇪', callingCode: '+353' },
  { code: 'IL', name: 'Israel', nativeName: 'יִשְׂרָאֵל', flag: '🇮🇱', callingCode: '+972' },
  { code: 'IT', name: 'Italy', nativeName: 'Italia', flag: '🇮🇹', callingCode: '+39' },
  { code: 'CI', name: 'Ivory Coast', nativeName: "Côte d'Ivoire", flag: '🇨🇮', callingCode: '+225' },
  { code: 'JM', name: 'Jamaica', nativeName: 'Jamaica', flag: '🇯🇲', callingCode: '+1876' },
  { code: 'JP', name: 'Japan', nativeName: '日本', flag: '🇯🇵', callingCode: '+81' },
  { code: 'JO', name: 'Jordan', nativeName: 'الأردن', flag: '🇯🇴', callingCode: '+962' },
  { code: 'KZ', name: 'Kazakhstan', nativeName: 'Қазақстан', flag: '🇰🇿', callingCode: '+7' },
  { code: 'KE', name: 'Kenya', nativeName: 'Kenya', flag: '🇰🇪', callingCode: '+254' },
  { code: 'KI', name: 'Kiribati', nativeName: 'Kiribati', flag: '🇰🇮', callingCode: '+686' },
  { code: 'KW', name: 'Kuwait', nativeName: 'الكويت', flag: '🇰🇼', callingCode: '+965' },
  { code: 'KG', name: 'Kyrgyzstan', nativeName: 'Кыргызстан', flag: '🇰🇬', callingCode: '+996' },
  { code: 'LA', name: 'Laos', nativeName: 'ລາວ', flag: '🇱🇦', callingCode: '+856' },
  { code: 'LV', name: 'Latvia', nativeName: 'Latvija', flag: '🇱🇻', callingCode: '+371' },
  { code: 'LB', name: 'Lebanon', nativeName: 'لبنان', flag: '🇱🇧', callingCode: '+961' },
  { code: 'LS', name: 'Lesotho', nativeName: 'Lesotho', flag: '🇱🇸', callingCode: '+266' },
  { code: 'LR', name: 'Liberia', nativeName: 'Liberia', flag: '🇱🇷', callingCode: '+231' },
  { code: 'LY', name: 'Libya', nativeName: 'ليبيا', flag: '🇱🇾', callingCode: '+218' },
  { code: 'LI', name: 'Liechtenstein', nativeName: 'Liechtenstein', flag: '🇱🇮', callingCode: '+423' },
  { code: 'LT', name: 'Lithuania', nativeName: 'Lietuva', flag: '🇱🇹', callingCode: '+370' },
  { code: 'LU', name: 'Luxembourg', nativeName: 'Luxembourg', flag: '🇱🇺', callingCode: '+352' },
  { code: 'MO', name: 'Macau', nativeName: '澳門', flag: '🇲🇴', callingCode: '+853' },
  { code: 'MG', name: 'Madagascar', nativeName: 'Madagasikara', flag: '🇲🇬', callingCode: '+261' },
  { code: 'MW', name: 'Malawi', nativeName: 'Malawi', flag: '🇲🇼', callingCode: '+265' },
  { code: 'MY', name: 'Malaysia', nativeName: 'Malaysia', flag: '🇲🇾', callingCode: '+60' },
  { code: 'MV', name: 'Maldives', nativeName: 'Maldives', flag: '🇲🇻', callingCode: '+960' },
  { code: 'ML', name: 'Mali', nativeName: 'Mali', flag: '🇲🇱', callingCode: '+223' },
  { code: 'MT', name: 'Malta', nativeName: 'Malta', flag: '🇲🇹', callingCode: '+356' },
  { code: 'MH', name: 'Marshall Islands', nativeName: 'Marshall Islands', flag: '🇲🇭', callingCode: '+692' },
  { code: 'MR', name: 'Mauritania', nativeName: 'موريتانيا', flag: '🇲🇷', callingCode: '+222' },
  { code: 'MU', name: 'Mauritius', nativeName: 'Mauritius', flag: '🇲🇺', callingCode: '+230' },
  { code: 'MX', name: 'Mexico', nativeName: 'México', flag: '🇲🇽', callingCode: '+52' },
  { code: 'FM', name: 'Micronesia', nativeName: 'Micronesia', flag: '🇫🇲', callingCode: '+691' },
  { code: 'MD', name: 'Moldova', nativeName: 'Moldova', flag: '🇲🇩', callingCode: '+373' },
  { code: 'MC', name: 'Monaco', nativeName: 'Monaco', flag: '🇲🇨', callingCode: '+377' },
  { code: 'MN', name: 'Mongolia', nativeName: 'Монгол', flag: '🇲🇳', callingCode: '+976' },
  { code: 'ME', name: 'Montenegro', nativeName: 'Црна Гора', flag: '🇲🇪', callingCode: '+382' },
  { code: 'MS', name: 'Montserrat', nativeName: 'Montserrat', flag: '🇲🇸', callingCode: '+1664' },
  { code: 'MA', name: 'Morocco', nativeName: 'المغرب', flag: '🇲🇦', callingCode: '+212' },
  { code: 'MZ', name: 'Mozambique', nativeName: 'Moçambique', flag: '🇲🇿', callingCode: '+258' },
  { code: 'MM', name: 'Myanmar', nativeName: 'မြန်မာ', flag: '🇲🇲', callingCode: '+95' },
  { code: 'NA', name: 'Namibia', nativeName: 'Namibia', flag: '🇳🇦', callingCode: '+264' },
  { code: 'NR', name: 'Nauru', nativeName: 'Nauru', flag: '🇳🇷', callingCode: '+674' },
  { code: 'NP', name: 'Nepal', nativeName: 'नेपाल', flag: '🇳🇵', callingCode: '+977' },
  { code: 'NL', name: 'Netherlands', nativeName: 'Nederland', flag: '🇳🇱', callingCode: '+31' },
  { code: 'NC', name: 'New Caledonia', nativeName: 'Nouvelle-Calédonie', flag: '🇳🇨', callingCode: '+687' },
  { code: 'NZ', name: 'New Zealand', nativeName: 'New Zealand', flag: '🇳🇿', callingCode: '+64' },
  { code: 'NI', name: 'Nicaragua', nativeName: 'Nicaragua', flag: '🇳🇮', callingCode: '+505' },
  { code: 'NE', name: 'Niger', nativeName: 'Niger', flag: '🇳🇪', callingCode: '+227' },
  { code: 'NG', name: 'Nigeria', nativeName: 'Nigeria', flag: '🇳🇬', callingCode: '+234' },
  { code: 'NU', name: 'Niue', nativeName: 'Niuē', flag: '🇳🇺', callingCode: '+683' },
  { code: 'KP', name: 'North Korea', nativeName: '조선', flag: '🇰🇵', callingCode: '+850' },
  { code: 'MK', name: 'North Macedonia', nativeName: 'Северна Македонија', flag: '🇲🇰', callingCode: '+389' },
  { code: 'NO', name: 'Norway', nativeName: 'Norge', flag: '🇳🇴', callingCode: '+47' },
  { code: 'OM', name: 'Oman', nativeName: 'عمان', flag: '🇴🇲', callingCode: '+968' },
  { code: 'PK', name: 'Pakistan', nativeName: 'پاکستان', flag: '🇵🇰', callingCode: '+92' },
  { code: 'PW', name: 'Palau', nativeName: 'Palau', flag: '🇵🇼', callingCode: '+680' },
  { code: 'PA', name: 'Panama', nativeName: 'Panamá', flag: '🇵🇦', callingCode: '+507' },
  { code: 'PG', name: 'Papua New Guinea', nativeName: 'Papua Niugini', flag: '🇵🇬', callingCode: '+675' },
  { code: 'PY', name: 'Paraguay', nativeName: 'Paraguay', flag: '🇵🇾', callingCode: '+595' },
  { code: 'PE', name: 'Peru', nativeName: 'Perú', flag: '🇵🇪', callingCode: '+51' },
  { code: 'PH', name: 'Philippines', nativeName: 'Pilipinas', flag: '🇵🇭', callingCode: '+63' },
  { code: 'PL', name: 'Poland', nativeName: 'Polska', flag: '🇵🇱', callingCode: '+48' },
  { code: 'PT', name: 'Portugal', nativeName: 'Portugal', flag: '🇵🇹', callingCode: '+351' },
  { code: 'PR', name: 'Puerto Rico', nativeName: 'Puerto Rico', flag: '🇵🇷', callingCode: '+1787' },
  { code: 'RE', name: 'Réunion', nativeName: 'La Réunion', flag: '🇷🇪', callingCode: '+262' },
  { code: 'RO', name: 'Romania', nativeName: 'România', flag: '🇷🇴', callingCode: '+40' },
  { code: 'RU', name: 'Russia', nativeName: 'Россия', flag: '🇷🇺', callingCode: '+7' },
  { code: 'RW', name: 'Rwanda', nativeName: 'Rwanda', flag: '🇷🇼', callingCode: '+250' },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    nativeName: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    callingCode: '+1869',
  },
  { code: 'LC', name: 'Saint Lucia', nativeName: 'Saint Lucia', flag: '🇱🇨', callingCode: '+1758' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    nativeName: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    callingCode: '+1784',
  },
  { code: 'WS', name: 'Samoa', nativeName: 'Samoa', flag: '🇼🇸', callingCode: '+685' },
  { code: 'SM', name: 'San Marino', nativeName: 'San Marino', flag: '🇸🇲', callingCode: '+378' },
  {
    code: 'ST',
    name: 'Sao Tome and Principe',
    nativeName: 'São Tomé e Príncipe',
    flag: '🇸🇹',
    callingCode: '+239',
  },
  { code: 'SA', name: 'Saudi Arabia', nativeName: 'السعودية', flag: '🇸🇦', callingCode: '+966' },
  { code: 'SN', name: 'Senegal', nativeName: 'Sénégal', flag: '🇸🇳', callingCode: '+221' },
  { code: 'RS', name: 'Serbia', nativeName: 'Србија', flag: '🇷🇸', callingCode: '+381' },
  { code: 'SC', name: 'Seychelles', nativeName: 'Seychelles', flag: '🇸🇨', callingCode: '+248' },
  { code: 'SL', name: 'Sierra Leone', nativeName: 'Sierra Leone', flag: '🇸🇱', callingCode: '+232' },
  { code: 'SG', name: 'Singapore', nativeName: 'Singapore', flag: '🇸🇬', callingCode: '+65' },
  { code: 'SX', name: 'Sint Maarten', nativeName: 'Sint Maarten', flag: '🇸🇽', callingCode: '+1721' },
  { code: 'SK', name: 'Slovakia', nativeName: 'Slovensko', flag: '🇸🇰', callingCode: '+421' },
  { code: 'SI', name: 'Slovenia', nativeName: 'Slovenija', flag: '🇸🇮', callingCode: '+386' },
  { code: 'SB', name: 'Solomon Islands', nativeName: 'Solomon Islands', flag: '🇸🇧', callingCode: '+677' },
  { code: 'SO', name: 'Somalia', nativeName: 'Somalia', flag: '🇸🇴', callingCode: '+252' },
  { code: 'ZA', name: 'South Africa', nativeName: 'South Africa', flag: '🇿🇦', callingCode: '+27' },
  { code: 'KR', name: 'South Korea', nativeName: '대한민국', flag: '🇰🇷', callingCode: '+82' },
  { code: 'SS', name: 'South Sudan', nativeName: 'South Sudan', flag: '🇸🇸', callingCode: '+211' },
  { code: 'ES', name: 'Spain', nativeName: 'España', flag: '🇪🇸', callingCode: '+34' },
  { code: 'LK', name: 'Sri Lanka', nativeName: 'ශ්‍රී ලංකාව', flag: '🇱🇰', callingCode: '+94' },
  { code: 'SD', name: 'Sudan', nativeName: 'السودان', flag: '🇸🇩', callingCode: '+249' },
  { code: 'SR', name: 'Suriname', nativeName: 'Suriname', flag: '🇸🇷', callingCode: '+597' },
  { code: 'SE', name: 'Sweden', nativeName: 'Sverige', flag: '🇸🇪', callingCode: '+46' },
  { code: 'CH', name: 'Switzerland', nativeName: 'Schweiz', flag: '🇨🇭', callingCode: '+41' },
  { code: 'SY', name: 'Syria', nativeName: 'سوريا', flag: '🇸🇾', callingCode: '+963' },
  { code: 'TW', name: 'Taiwan', nativeName: '臺灣', flag: '🇹🇼', callingCode: '+886' },
  { code: 'TJ', name: 'Tajikistan', nativeName: 'Тоҷикистон', flag: '🇹🇯', callingCode: '+992' },
  { code: 'TZ', name: 'Tanzania', nativeName: 'Tanzania', flag: '🇹🇿', callingCode: '+255' },
  { code: 'TH', name: 'Thailand', nativeName: 'ประเทศไทย', flag: '🇹🇭', callingCode: '+66' },
  { code: 'TL', name: 'Timor-Leste', nativeName: 'Timor-Leste', flag: '🇹🇱', callingCode: '+670' },
  { code: 'TG', name: 'Togo', nativeName: 'Togo', flag: '🇹🇬', callingCode: '+228' },
  { code: 'TK', name: 'Tokelau', nativeName: 'Tokelau', flag: '🇹🇰', callingCode: '+690' },
  { code: 'TO', name: 'Tonga', nativeName: 'Tonga', flag: '🇹🇴', callingCode: '+676' },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    nativeName: 'Trinidad and Tobago',
    flag: '🇹🇹',
    callingCode: '+1868',
  },
  { code: 'TN', name: 'Tunisia', nativeName: 'تونس', flag: '🇹🇳', callingCode: '+216' },
  { code: 'TR', name: 'Turkey', nativeName: 'Türkiye', flag: '🇹🇷', callingCode: '+90' },
  { code: 'TM', name: 'Turkmenistan', nativeName: 'Türkmenistan', flag: '🇹🇲', callingCode: '+993' },
  { code: 'TV', name: 'Tuvalu', nativeName: 'Tuvalu', flag: '🇹🇻', callingCode: '+688' },
  { code: 'UG', name: 'Uganda', nativeName: 'Uganda', flag: '🇺🇬', callingCode: '+256' },
  { code: 'UA', name: 'Ukraine', nativeName: 'Україна', flag: '🇺🇦', callingCode: '+380' },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    nativeName: 'الإمارات العربية المتحدة',
    flag: '🇦🇪',
    callingCode: '+971',
  },
  { code: 'GB', name: 'United Kingdom', nativeName: 'United Kingdom', flag: '🇬🇧', callingCode: '+44' },
  { code: 'US', name: 'United States', nativeName: 'United States', flag: '🇺🇸', callingCode: '+1' },
  { code: 'CA', name: 'Canada', nativeName: 'Canada', flag: '🇨🇦', callingCode: '+1' },
  { code: 'UY', name: 'Uruguay', nativeName: 'Uruguay', flag: '🇺🇾', callingCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', nativeName: 'O‘zbekiston', flag: '🇺🇿', callingCode: '+998' },
  { code: 'VU', name: 'Vanuatu', nativeName: 'Vanuatu', flag: '🇻🇺', callingCode: '+678' },
  { code: 'VA', name: 'Vatican City', nativeName: 'Vaticano', flag: '🇻🇦', callingCode: '+379' },
  { code: 'VE', name: 'Venezuela', nativeName: 'Venezuela', flag: '🇻🇪', callingCode: '+58' },
  { code: 'VN', name: 'Vietnam', nativeName: 'Việt Nam', flag: '🇻🇳', callingCode: '+84' },
  { code: 'YE', name: 'Yemen', nativeName: 'اليمن', flag: '🇾🇪', callingCode: '+967' },
  { code: 'ZM', name: 'Zambia', nativeName: 'Zambia', flag: '🇿🇲', callingCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', nativeName: 'Zimbabwe', flag: '🇿🇼', callingCode: '+263' },
];

export const LANGUAGES = [
  {
    value: 'aa',
    label: 'Afar',
    native: 'Afar',
  },
  {
    value: 'ab',
    label: 'Abkhazian',
    native: 'Аҧсуа',
  },
  {
    value: 'af',
    label: 'Afrikaans',
    native: 'Afrikaans',
  },
  {
    value: 'ak',
    label: 'Akan',
    native: 'Akana',
  },
  {
    value: 'am',
    label: 'Amharic',
    native: 'አማርኛ',
  },
  {
    value: 'an',
    label: 'Aragonese',
    native: 'Aragonés',
  },
  {
    value: 'ar',
    label: 'Arabic',
    native: 'العربية',
    rtl: 1,
  },
  {
    value: 'as',
    label: 'Assamese',
    native: 'অসমীয়া',
  },
  {
    value: 'av',
    label: 'Avar',
    native: 'Авар',
  },
  {
    value: 'ay',
    label: 'Aymara',
    native: 'Aymar',
  },
  {
    value: 'az',
    label: 'Azerbaijani',
    native: 'Azərbaycanca',
  },
  {
    value: 'ba',
    label: 'Bashkir',
    native: 'Башҡорт',
  },
  {
    value: 'be',
    label: 'Belarusian',
    native: 'Беларуская',
  },
  {
    value: 'bg',
    label: 'Bulgarian',
    native: 'Български',
  },
  {
    value: 'bh',
    label: 'Bihari',
    native: 'भोजपुरी',
  },
  {
    value: 'bi',
    label: 'Bislama',
    native: 'Bislama',
  },
  {
    value: 'bm',
    label: 'Bambara',
    native: 'Bamanankan',
  },
  {
    value: 'bn',
    label: 'Bengali',
    native: 'বাংলা',
  },
  {
    value: 'bo',
    label: 'Tibetan',
    native: 'བོད་ཡིག / Bod skad',
  },
  {
    value: 'br',
    label: 'Breton',
    native: 'Brezhoneg',
  },
  {
    value: 'bs',
    label: 'Bosnian',
    native: 'Bosanski',
  },
  {
    value: 'ca',
    label: 'Catalan',
    native: 'Català',
  },
  {
    value: 'ce',
    label: 'Chechen',
    native: 'Нохчийн',
  },
  {
    value: 'ch',
    label: 'Chamorro',
    native: 'Chamoru',
  },
  {
    value: 'co',
    label: 'Corsican',
    native: 'Corsu',
  },
  {
    value: 'cr',
    label: 'Cree',
    native: 'Nehiyaw',
  },
  {
    value: 'cs',
    label: 'Czech',
    native: 'Česky',
  },
  {
    value: 'cu',
    label: 'Old Church Slavonic / Old Bulgarian',
    native: 'словѣньскъ / slověnĭskŭ',
  },
  {
    value: 'cv',
    label: 'Chuvash',
    native: 'Чăваш',
  },
  {
    value: 'cy',
    label: 'Welsh',
    native: 'Cymraeg',
  },
  {
    value: 'da',
    label: 'Danish',
    native: 'Dansk',
  },
  {
    value: 'de',
    label: 'German',
    native: 'Deutsch',
  },
  {
    value: 'dv',
    label: 'Divehi',
    native: 'ދިވެހިބަސް',
    rtl: 1,
  },
  {
    value: 'dz',
    label: 'Dzongkha',
    native: 'ཇོང་ཁ',
  },
  {
    value: 'ee',
    label: 'Ewe',
    native: 'Ɛʋɛ',
  },
  {
    value: 'el',
    label: 'Greek',
    native: 'Ελληνικά',
  },
  {
    value: 'en',
    label: 'English',
    native: 'English',
  },
  {
    value: 'eo',
    label: 'Esperanto',
    native: 'Esperanto',
  },
  {
    value: 'es',
    label: 'Spanish',
    native: 'Español',
  },
  {
    value: 'et',
    label: 'Estonian',
    native: 'Eesti',
  },
  {
    value: 'eu',
    label: 'Basque',
    native: 'Euskara',
  },
  {
    value: 'fa',
    label: 'Persian',
    native: 'فارسی',
    rtl: 1,
  },
  {
    value: 'ff',
    label: 'Peul',
    native: 'Fulfulde',
  },
  {
    value: 'fi',
    label: 'Finnish',
    native: 'Suomi',
  },
  {
    value: 'fj',
    label: 'Fijian',
    native: 'Na Vosa Vakaviti',
  },
  {
    value: 'fo',
    label: 'Faroese',
    native: 'Føroyskt',
  },
  {
    value: 'fr',
    label: 'French',
    native: 'Français',
  },
  {
    value: 'fy',
    label: 'West Frisian',
    native: 'Frysk',
  },
  {
    value: 'ga',
    label: 'Irish',
    native: 'Gaeilge',
  },
  {
    value: 'gd',
    label: 'Scottish Gaelic',
    native: 'Gàidhlig',
  },
  {
    value: 'gl',
    label: 'Galician',
    native: 'Galego',
  },
  {
    value: 'gn',
    label: 'Guarani',
    native: "Avañe'ẽ",
  },
  {
    value: 'gu',
    label: 'Gujarati',
    native: 'ગુજરાતી',
  },
  {
    value: 'gv',
    label: 'Manx',
    native: 'Gaelg',
  },
  {
    value: 'ha',
    label: 'Hausa',
    native: 'هَوُسَ',
    rtl: 1,
  },
  {
    value: 'he',
    label: 'Hebrew',
    native: 'עברית',
    rtl: 1,
  },
  {
    value: 'hi',
    label: 'Hindi',
    native: 'हिन्दी',
  },
  {
    value: 'ho',
    label: 'Hiri Motu',
    native: 'Hiri Motu',
  },
  {
    value: 'hr',
    label: 'Croatian',
    native: 'Hrvatski',
  },
  {
    value: 'ht',
    label: 'Haitian',
    native: 'Krèyol ayisyen',
  },
  {
    value: 'hu',
    label: 'Hungarian',
    native: 'Magyar',
  },
  {
    value: 'hy',
    label: 'Armenian',
    native: 'Հայերեն',
  },
  {
    value: 'hz',
    label: 'Herero',
    native: 'Otsiherero',
  },
  {
    value: 'ia',
    label: 'Interlingua',
    native: 'Interlingua',
  },
  {
    value: 'id',
    label: 'Indonesian',
    native: 'Bahasa Indonesia',
  },
  {
    value: 'ie',
    label: 'Interlingue',
    native: 'Interlingue',
  },
  {
    value: 'ig',
    label: 'Igbo',
    native: 'Igbo',
  },
  {
    value: 'ii',
    label: 'Sichuan Yi',
    native: 'ꆇꉙ / 四川彝语',
  },
  {
    value: 'ik',
    label: 'Inupiak',
    native: 'Iñupiak',
  },
  {
    value: 'io',
    label: 'Ido',
    native: 'Ido',
  },
  {
    value: 'is',
    label: 'Icelandic',
    native: 'Íslenska',
  },
  {
    value: 'it',
    label: 'Italian',
    native: 'Italiano',
  },
  {
    value: 'iu',
    label: 'Inuktitut',
    native: 'ᐃᓄᒃᑎᑐᑦ',
  },
  {
    value: 'ja',
    label: 'Japanese',
    native: '日本語',
  },
  {
    value: 'jv',
    label: 'Javanese',
    native: 'Basa Jawa',
  },
  {
    value: 'ka',
    label: 'Georgian',
    native: 'ქართული',
  },
  {
    value: 'kg',
    label: 'Kongo',
    native: 'KiKongo',
  },
  {
    value: 'ki',
    label: 'Kikuyu',
    native: 'Gĩkũyũ',
  },
  {
    value: 'kj',
    label: 'Kuanyama',
    native: 'Kuanyama',
  },
  {
    value: 'kk',
    label: 'Kazakh',
    native: 'Қазақша',
  },
  {
    value: 'kl',
    label: 'Greenlandic',
    native: 'Kalaallisut',
  },
  {
    value: 'km',
    label: 'Cambodian',
    native: 'ភាសាខ្មែរ',
  },
  {
    value: 'kn',
    label: 'Kannada',
    native: 'ಕನ್ನಡ',
  },
  {
    value: 'ko',
    label: 'Korean',
    native: '한국어',
  },
  {
    value: 'kr',
    label: 'Kanuri',
    native: 'Kanuri',
  },
  {
    value: 'ks',
    label: 'Kashmiri',
    native: 'कश्मीरी / كشميري',
    rtl: 1,
  },
  {
    value: 'ku',
    label: 'Kurdish',
    native: 'Kurdî / كوردی',
    rtl: 1,
  },
  {
    value: 'kv',
    label: 'Komi',
    native: 'Коми',
  },
  {
    value: 'kw',
    label: 'Cornish',
    native: 'Kernewek',
  },
  {
    value: 'ky',
    label: 'Kirghiz',
    native: 'Kırgızca / Кыргызча',
  },
  {
    value: 'la',
    label: 'Latin',
    native: 'Latina',
  },
  {
    value: 'lb',
    label: 'Luxembourgish',
    native: 'Lëtzebuergesch',
  },
  {
    value: 'lg',
    label: 'Ganda',
    native: 'Luganda',
  },
  {
    value: 'li',
    label: 'Limburgian',
    native: 'Limburgs',
  },
  {
    value: 'ln',
    label: 'Lingala',
    native: 'Lingála',
  },
  {
    value: 'lo',
    label: 'Laotian',
    native: 'ລາວ / Pha xa lao',
  },
  {
    value: 'lt',
    label: 'Lithuanian',
    native: 'Lietuvių',
  },
  {
    value: 'lu',
    label: 'Luba-Katanga',
    native: 'Tshiluba',
  },
  {
    value: 'lv',
    label: 'Latvian',
    native: 'Latviešu',
  },
  {
    value: 'mg',
    label: 'Malagasy',
    native: 'Malagasy',
  },
  {
    value: 'mh',
    label: 'Marshallese',
    native: 'Kajin Majel / Ebon',
  },
  {
    value: 'mi',
    label: 'Maori',
    native: 'Māori',
  },
  {
    value: 'mk',
    label: 'Macedonian',
    native: 'Македонски',
  },
  {
    value: 'ml',
    label: 'Malayalam',
    native: 'മലയാളം',
  },
  {
    value: 'mn',
    label: 'Mongolian',
    native: 'Монгол',
  },
  {
    value: 'mo',
    label: 'Moldovan',
    native: 'Moldovenească',
  },
  {
    value: 'mr',
    label: 'Marathi',
    native: 'मराठी',
  },
  {
    value: 'ms',
    label: 'Malay',
    native: 'Bahasa Melayu',
  },
  {
    value: 'mt',
    label: 'Maltese',
    native: 'bil-Malti',
  },
  {
    value: 'my',
    label: 'Burmese',
    native: 'မြန်မာစာ',
  },
  {
    value: 'na',
    label: 'Nauruan',
    native: 'Dorerin Naoero',
  },
  {
    value: 'nb',
    label: 'Norwegian Bokmål',
    native: 'Norsk bokmål',
  },
  {
    value: 'nd',
    label: 'North Ndebele',
    native: 'Sindebele',
  },
  {
    value: 'ne',
    label: 'Nepali',
    native: 'नेपाली',
  },
  {
    value: 'ng',
    label: 'Ndonga',
    native: 'Oshiwambo',
  },
  {
    value: 'nl',
    label: 'Dutch',
    native: 'Nederlands',
  },
  {
    value: 'nn',
    label: 'Norwegian Nynorsk',
    native: 'Norsk nynorsk',
  },
  {
    value: 'no',
    label: 'Norwegian',
    native: 'Norsk',
  },
  {
    value: 'nr',
    label: 'South Ndebele',
    native: 'isiNdebele',
  },
  {
    value: 'nv',
    label: 'Navajo',
    native: 'Diné bizaad',
  },
  {
    value: 'ny',
    label: 'Chichewa',
    native: 'Chi-Chewa',
  },
  {
    value: 'oc',
    label: 'Occitan',
    native: 'Occitan',
  },
  {
    value: 'oj',
    label: 'Ojibwa',
    native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin',
  },
  {
    value: 'om',
    label: 'Oromo',
    native: 'Oromoo',
  },
  {
    value: 'or',
    label: 'Oriya',
    native: 'ଓଡ଼ିଆ',
  },
  {
    value: 'os',
    label: 'Ossetian / Ossetic',
    native: 'Иронау',
  },
  {
    value: 'pa',
    label: 'Panjabi / Punjabi',
    native: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
  },
  {
    value: 'pi',
    label: 'Pali',
    native: 'Pāli / पाऴि',
  },
  {
    value: 'pl',
    label: 'Polish',
    native: 'Polski',
  },
  {
    value: 'ps',
    label: 'Pashto',
    native: 'پښتو',
    rtl: 1,
  },
  {
    value: 'pt',
    label: 'Portuguese',
    native: 'Português',
  },
  {
    value: 'qu',
    label: 'Quechua',
    native: 'Runa Simi',
  },
  {
    value: 'rm',
    label: 'Raeto Romance',
    native: 'Rumantsch',
  },
  {
    value: 'rn',
    label: 'Kirundi',
    native: 'Kirundi',
  },
  {
    value: 'ro',
    label: 'Romanian',
    native: 'Română',
  },
  {
    value: 'ru',
    label: 'Russian',
    native: 'Русский',
  },
  {
    value: 'rw',
    label: 'Rwandi',
    native: 'Kinyarwandi',
  },
  {
    value: 'sa',
    label: 'Sanskrit',
    native: 'संस्कृतम्',
  },
  {
    value: 'sc',
    label: 'Sardinian',
    native: 'Sardu',
  },
  {
    value: 'sd',
    label: 'Sindhi',
    native: 'सिनधि',
  },
  {
    value: 'se',
    label: 'Northern Sami',
    native: 'Sámegiella',
  },
  {
    value: 'sg',
    label: 'Sango',
    native: 'Sängö',
  },
  {
    value: 'sh',
    label: 'Serbo-Croatian',
    native: 'Srpskohrvatski / Српскохрватски',
  },
  {
    value: 'si',
    label: 'Sinhalese',
    native: 'සිංහල',
  },
  {
    value: 'sk',
    label: 'Slovak',
    native: 'Slovenčina',
  },
  {
    value: 'sl',
    label: 'Slovenian',
    native: 'Slovenščina',
  },
  {
    value: 'sm',
    label: 'Samoan',
    native: 'Gagana Samoa',
  },
  {
    value: 'sn',
    label: 'Shona',
    native: 'chiShona',
  },
  {
    value: 'so',
    label: 'Somalia',
    native: 'Soomaaliga',
  },
  {
    value: 'sq',
    label: 'Albanian',
    native: 'Shqip',
  },
  {
    value: 'sr',
    label: 'Serbian',
    native: 'Српски',
  },
  {
    value: 'ss',
    label: 'Swati',
    native: 'SiSwati',
  },
  {
    value: 'st',
    label: 'Southern Sotho',
    native: 'Sesotho',
  },
  {
    value: 'su',
    label: 'Sundanese',
    native: 'Basa Sunda',
  },
  {
    value: 'sv',
    label: 'Swedish',
    native: 'Svenska',
  },
  {
    value: 'sw',
    label: 'Swahili',
    native: 'Kiswahili',
  },
  {
    value: 'ta',
    label: 'Tamil',
    native: 'தமிழ்',
  },
  {
    value: 'te',
    label: 'Telugu',
    native: 'తెలుగు',
  },
  {
    value: 'tg',
    label: 'Tajik',
    native: 'Тоҷикӣ',
  },
  {
    value: 'th',
    label: 'Thai',
    native: 'ไทย / Phasa Thai',
  },
  {
    value: 'ti',
    label: 'Tigrinya',
    native: 'ትግርኛ',
  },
  {
    value: 'tk',
    label: 'Turkmen',
    native: 'Туркмен / تركمن',
  },
  {
    value: 'tl',
    label: 'Tagalog / Filipino',
    native: 'Tagalog',
  },
  {
    value: 'tn',
    label: 'Tswana',
    native: 'Setswana',
  },
  {
    value: 'to',
    label: 'Tonga',
    native: 'Lea Faka-Tonga',
  },
  {
    value: 'tr',
    label: 'Turkish',
    native: 'Türkçe',
  },
  {
    value: 'ts',
    label: 'Tsonga',
    native: 'Xitsonga',
  },
  {
    value: 'tt',
    label: 'Tatar',
    native: 'Tatarça',
  },
  {
    value: 'tw',
    label: 'Twi',
    native: 'Twi',
  },
  {
    value: 'ty',
    label: 'Tahitian',
    native: 'Reo Mā`ohi',
  },
  {
    value: 'ug',
    label: 'Uyghur',
    native: 'Uyƣurqə / ئۇيغۇرچە',
  },
  {
    value: 'uk',
    label: 'Ukrainian',
    native: 'Українська',
  },
  {
    value: 'ur',
    label: 'Urdu',
    native: 'اردو',
    rtl: 1,
  },
  {
    value: 'uz',
    label: 'Uzbek',
    native: 'Ўзбек',
  },
  {
    value: 've',
    label: 'Venda',
    native: 'Tshivenḓa',
  },
  {
    value: 'vi',
    label: 'Vietnamese',
    native: 'Tiếng Việt',
  },
  {
    value: 'vo',
    label: 'Volapük',
    native: 'Volapük',
  },
  {
    value: 'wa',
    label: 'Walloon',
    native: 'Walon',
  },
  {
    value: 'wo',
    label: 'Wolof',
    native: 'Wollof',
  },
  {
    value: 'xh',
    label: 'Xhosa',
    native: 'isiXhosa',
  },
  {
    value: 'yi',
    label: 'Yiddish',
    native: 'ייִדיש',
    rtl: 1,
  },
  {
    value: 'yo',
    label: 'Yoruba',
    native: 'Yorùbá',
  },
  {
    value: 'za',
    label: 'Zhuang',
    native: 'Cuengh / Tôô / 壮语',
  },
  {
    value: 'zh',
    label: 'Chinese',
    native: '中文',
  },
  {
    value: 'zu',
    label: 'Zulu',
    native: 'isiZulu',
  },
];


export const MONTHLY_GOAL_TYPES = [
  {name: 'Weight Management', value: 'weight management'},
  {name: "Sleep & energy", value: 'sleep and energy'},
  {name: 'Hormon Balance', value: 'hormon balance'},
  {name: 'Nutrition', value: 'nutrition'},
  {name: 'Exercise', value: 'exercise'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
  {name: 'Relationship', value: 'relationship'},
]

export const BUSINESS_MODELS = [
  {label: 'Wellness Coach / Practitioner', value: 'wellness coach / practitioner'},
  {label: 'Gym / Studio Owner', value: 'gym / studio owner'},
  {label: 'Wellness Retailer', value: 'wellness retailer'},
  {label: 'Blogger / Content Creator', value: 'blogger / content creator'},
  {label: 'Podcast Host', value: 'podcast host'},
  {label: 'Online Program Seller', value: 'online program seller'},
  {label: 'Affiliate Marketer', value: 'affiliate marketer'},
  {label: 'Other', value: 'other'},
]

export const TITLE_OPTIONS = [
  { value: 'Mr.', label: 'Mr.' },
  { value: 'Mrs.', label: 'Mrs.' },
  { value: 'Ms.', label: 'Ms.' },
  // { value: 'Miss', label: 'Miss' },
  // { value: 'Dr.', label: 'Dr.' },
  // { value: 'Prof.', label: 'Prof.' },
  // { value: 'Coach', label: 'Coach' },
  // { value: 'Master', label: 'Master' },
];
