const queryKeys = {
  users: 'users',
  loggedInUser: 'loggedInUser',
  onboardingQuiz: 'onboardingQuiz',
  lmsCategories: 'lmsCategories',
  lmsFeaturedCategories: 'lmsFeaturedCategories',
  lmsTags: 'lmsTags',
  lmsExperts: 'lmsExperts',
  lmsQuizes: 'lmsQuizes',
  lmsImageSessions: 'lmsImageSessions',
  lmsAudioSessions: 'lmsAudioSessions',
  lmsVideoSessions: 'lmsVideoSessions',
  lmsModules: 'lmsModules',
  lmsPrograms: 'lmsPrograms',
  subscriptionPages: 'subscriptionPages',
  subscriptionPlans: 'subscriptionPlans',
  stripeCheckoutSessions: 'stripeCheckoutSessions',
  customerQuizes: 'customerQuizes',
  customerPrograms: 'customerPrograms',
  customerModules: 'customerModules',
  customerImageSessions: 'customerImageSessions',
  customerAudioSessions: 'customerAudioSessions',
  customerVideoSessions: 'customerVideoSessions',
  inboxConversations: 'inboxConversations',
  chatGroups: 'chatGroups',
};

export default queryKeys;
